version: "3"
services:
  database:
    restart: always
    image: postgis/postgis:13-master
    volumes:
      - pgd:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - '5431:5431'

  web:
    command: dotnet OurChat.dll --environment=prod
    environment:
      ASPNETCORE_ENVIRONMENT: prod
    restart: always
    build:
      context: .
      dockerfile: OurChat/Dockerfile
  
  nginx:
    ports:
    - '8080:80'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

  cache:
    image: redis:alpine3.16
    ports:
      - '6379:6379'
      
volumes:
  pgd:

networks:
  default:
    name: nginx