version: "3"
services:
  database:
    restart: always
    image: postgis/postgis:13-master
    volumes:
      - pgd:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgers
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres

  web:
    command: dotnet Test.dll --environment=prod
    environment:
      ASPNETCORE_ENVIRONMENT: prod
    restart: always
    build:
      context: .
      dockerfile: Test/Dockerfile
  
  nginx:
    ports:
    - '8080:80'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

  cache:
    image: redis:3.0.504-nanoserver
    ports:
      - 6379:6379
      
volumes:
  pgd:

networks:
  default:
    name: nginx